# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ecgandppgmonitor.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(911, 540)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(911, 540))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(911, 540))
        self.centralwidget.setMaximumSize(QSize(911, 540))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 911, 541))
        self.tab_monitor = QWidget()
        self.tab_monitor.setObjectName(u"tab_monitor")
        self.ppg = PlotWidget(self.tab_monitor)
        self.ppg.setObjectName(u"ppg")
        self.ppg.setGeometry(QRect(10, 10, 661, 221))
        self.setting = QGroupBox(self.tab_monitor)
        self.setting.setObjectName(u"setting")
        self.setting.setGeometry(QRect(680, 100, 221, 241))
        self.setting.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.sampleAverage = QComboBox(self.setting)
        self.sampleAverage.addItem("")
        self.sampleAverage.addItem("")
        self.sampleAverage.addItem("")
        self.sampleAverage.addItem("")
        self.sampleAverage.addItem("")
        self.sampleAverage.addItem("")
        self.sampleAverage.setObjectName(u"sampleAverage")
        self.sampleAverage.setGeometry(QRect(110, 50, 101, 22))
        self.label = QLabel(self.setting)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 91, 21))
        self.label_2 = QLabel(self.setting)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 91, 21))
        self.label_3 = QLabel(self.setting)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 91, 21))
        self.ledMode = QComboBox(self.setting)
        self.ledMode.addItem("")
        self.ledMode.addItem("")
        self.ledMode.setObjectName(u"ledMode")
        self.ledMode.setGeometry(QRect(110, 80, 101, 22))
        self.label_4 = QLabel(self.setting)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 110, 91, 21))
        self.sampleRate = QComboBox(self.setting)
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.setObjectName(u"sampleRate")
        self.sampleRate.setGeometry(QRect(110, 110, 101, 22))
        self.label_5 = QLabel(self.setting)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 140, 91, 21))
        self.pulseWidth = QComboBox(self.setting)
        self.pulseWidth.addItem("")
        self.pulseWidth.addItem("")
        self.pulseWidth.addItem("")
        self.pulseWidth.addItem("")
        self.pulseWidth.setObjectName(u"pulseWidth")
        self.pulseWidth.setGeometry(QRect(110, 140, 101, 22))
        self.label_6 = QLabel(self.setting)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 170, 91, 21))
        self.adcRange = QComboBox(self.setting)
        self.adcRange.addItem("")
        self.adcRange.addItem("")
        self.adcRange.addItem("")
        self.adcRange.addItem("")
        self.adcRange.setObjectName(u"adcRange")
        self.adcRange.setGeometry(QRect(110, 170, 101, 22))
        self.ledBrightness = QSpinBox(self.setting)
        self.ledBrightness.setObjectName(u"ledBrightness")
        self.ledBrightness.setGeometry(QRect(110, 20, 101, 22))
        self.ledBrightness.setMaximum(255)
        self.ledBrightness.setValue(70)
        self.setSetting = QPushButton(self.setting)
        self.setSetting.setObjectName(u"setSetting")
        self.setSetting.setGeometry(QRect(60, 210, 91, 23))
        self.save = QGroupBox(self.tab_monitor)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(10, 460, 661, 51))
        self.save.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.path = QLineEdit(self.save)
        self.path.setObjectName(u"path")
        self.path.setGeometry(QRect(90, 20, 381, 20))
        self.path.setClearButtonEnabled(False)
        self.label_8 = QLabel(self.save)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 71, 20))
        font = QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.browse = QToolButton(self.save)
        self.browse.setObjectName(u"browse")
        self.browse.setGeometry(QRect(480, 20, 25, 20))
        self.setSaveState = QPushButton(self.save)
        self.setSaveState.setObjectName(u"setSaveState")
        self.setSaveState.setGeometry(QRect(520, 20, 61, 23))
        self.setSaveState.setAutoDefault(False)
        self.pauseSave = QPushButton(self.save)
        self.pauseSave.setObjectName(u"pauseSave")
        self.pauseSave.setEnabled(False)
        self.pauseSave.setGeometry(QRect(590, 20, 61, 23))
        self.plot = QGroupBox(self.tab_monitor)
        self.plot.setObjectName(u"plot")
        self.plot.setGeometry(QRect(680, 340, 221, 171))
        self.plot.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.setNsample = QPushButton(self.plot)
        self.setNsample.setObjectName(u"setNsample")
        self.setNsample.setGeometry(QRect(130, 40, 61, 23))
        self.label_7 = QLabel(self.plot)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 20, 91, 21))
        self.Nsample = QSpinBox(self.plot)
        self.Nsample.setObjectName(u"Nsample")
        self.Nsample.setGeometry(QRect(20, 40, 101, 22))
        self.Nsample.setAccelerated(True)
        self.Nsample.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.Nsample.setMinimum(25)
        self.Nsample.setMaximum(200)
        self.Nsample.setValue(50)
        self.setPlotSize = QPushButton(self.plot)
        self.setPlotSize.setObjectName(u"setPlotSize")
        self.setPlotSize.setGeometry(QRect(130, 90, 61, 23))
        self.label_10 = QLabel(self.plot)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 70, 81, 21))
        self.plotSize = QSpinBox(self.plot)
        self.plotSize.setObjectName(u"plotSize")
        self.plotSize.setGeometry(QRect(20, 90, 101, 22))
        self.plotSize.setAccelerated(True)
        self.plotSize.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.plotSize.setMinimum(1000)
        self.plotSize.setMaximum(10000)
        self.plotSize.setSingleStep(100)
        self.plotSize.setValue(1000)
        self.setPlotState = QPushButton(self.plot)
        self.setPlotState.setObjectName(u"setPlotState")
        self.setPlotState.setGeometry(QRect(60, 130, 91, 23))
        self.ecg = PlotWidget(self.tab_monitor)
        self.ecg.setObjectName(u"ecg")
        self.ecg.setGeometry(QRect(10, 240, 661, 221))
        self.logo = QLabel(self.tab_monitor)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(710, 10, 162, 81))
        self.logo.setPixmap(QPixmap(u"Kmitl.jpg"))
        self.tabWidget.addTab(self.tab_monitor, "")
        self.tab_advance = QWidget()
        self.tab_advance.setObjectName(u"tab_advance")
        self.groupBox = QGroupBox(self.tab_advance)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 311, 91))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 20, 71, 16))
        self.boardStatus = QLabel(self.groupBox)
        self.boardStatus.setObjectName(u"boardStatus")
        self.boardStatus.setGeometry(QRect(100, 20, 191, 16))
        self.tabWidget.addTab(self.tab_advance, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.ledMode.setCurrentIndex(1)
        self.sampleRate.setCurrentIndex(3)
        self.pulseWidth.setCurrentIndex(3)
        self.adcRange.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ECG & SpO2 Monitor", None))
        self.setting.setTitle(QCoreApplication.translate("MainWindow", u"PPG Setting", None))
        self.sampleAverage.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.sampleAverage.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.sampleAverage.setItemText(2, QCoreApplication.translate("MainWindow", u"4", None))
        self.sampleAverage.setItemText(3, QCoreApplication.translate("MainWindow", u"8", None))
        self.sampleAverage.setItemText(4, QCoreApplication.translate("MainWindow", u"16", None))
        self.sampleAverage.setItemText(5, QCoreApplication.translate("MainWindow", u"32", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"LED Brightness", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sample Average", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"LED Mode", None))
        self.ledMode.setItemText(0, QCoreApplication.translate("MainWindow", u"Red only", None))
        self.ledMode.setItemText(1, QCoreApplication.translate("MainWindow", u"Red + IR", None))

        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Sampling Rate", None))
        self.sampleRate.setItemText(0, QCoreApplication.translate("MainWindow", u"50", None))
        self.sampleRate.setItemText(1, QCoreApplication.translate("MainWindow", u"100", None))
        self.sampleRate.setItemText(2, QCoreApplication.translate("MainWindow", u"200", None))
        self.sampleRate.setItemText(3, QCoreApplication.translate("MainWindow", u"400", None))
        self.sampleRate.setItemText(4, QCoreApplication.translate("MainWindow", u"800", None))
        self.sampleRate.setItemText(5, QCoreApplication.translate("MainWindow", u"1000", None))
        self.sampleRate.setItemText(6, QCoreApplication.translate("MainWindow", u"1600", None))
        self.sampleRate.setItemText(7, QCoreApplication.translate("MainWindow", u"3200", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Pulse Width", None))
        self.pulseWidth.setItemText(0, QCoreApplication.translate("MainWindow", u"69", None))
        self.pulseWidth.setItemText(1, QCoreApplication.translate("MainWindow", u"118", None))
        self.pulseWidth.setItemText(2, QCoreApplication.translate("MainWindow", u"215", None))
        self.pulseWidth.setItemText(3, QCoreApplication.translate("MainWindow", u"411", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ADC Range", None))
        self.adcRange.setItemText(0, QCoreApplication.translate("MainWindow", u"2048", None))
        self.adcRange.setItemText(1, QCoreApplication.translate("MainWindow", u"4096", None))
        self.adcRange.setItemText(2, QCoreApplication.translate("MainWindow", u"8192", None))
        self.adcRange.setItemText(3, QCoreApplication.translate("MainWindow", u"16384", None))

        self.ledBrightness.setSuffix(QCoreApplication.translate("MainWindow", u" mA", None))
        self.setSetting.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.save.setTitle(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Path to file", None))
        self.browse.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.setSaveState.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pauseSave.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.plot.setTitle(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.setNsample.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Transmitted size", None))
#if QT_CONFIG(whatsthis)
        self.Nsample.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.Nsample.setSuffix(QCoreApplication.translate("MainWindow", u" sample", None))
        self.setPlotSize.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Plot size", None))
#if QT_CONFIG(whatsthis)
        self.plotSize.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.plotSize.setSuffix(QCoreApplication.translate("MainWindow", u" sample", None))
        self.setPlotState.setText(QCoreApplication.translate("MainWindow", u"Start Plotting", None))
        self.logo.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_monitor), QCoreApplication.translate("MainWindow", u"Monitor", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Status", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Board status :", None))
        self.boardStatus.setText(QCoreApplication.translate("MainWindow", u"Unknown", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advance), QCoreApplication.translate("MainWindow", u"Advance", None))
    # retranslateUi

